//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVE_Manufact.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVE_Manufact.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Ore Type	Uncompressed Volume	Compressed Volume	Tritanium	Pyerite	Mexallon	Isogen	Nocxium	Megacyte	Zydrine	Morphite	Location
        ///Veldspar	0.1	0.15	415								1.0 (All Space)	1230	28432	12195
        ///Concentrated Veldspar (+5%)	0.1	0.15	436								1.0 (All Space)	17470	28430
        ///Dense Veldspar (+10%)	0.1	0.15	457								1.0 (All Space)	17471	28431
        ///Scordite	0.15	0.19	346	173							1.0 (All Space)	1228	28429	12193
        ///Condensed Scordite (+5%)	0.15	0.19	364	182							1.0 (All Space)	17463	28427
        ///Massive Scordite (+10%)	0.15	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string minerals {
            get {
                return ResourceManager.GetString("minerals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //REGIONID	REGIONNAME
        ///10000001	Derelik
        ///10000002	The Forge
        ///10000003	Vale of the Silent
        ///10000004	UUA-F4
        ///10000005	Detorid
        ///10000006	Wicked Creek
        ///10000007	Cache
        ///10000008	Scalding Pass
        ///10000009	Insmother
        ///10000010	Tribute
        ///10000011	Great Wildlands
        ///10000012	Curse
        ///10000013	Malpais
        ///10000014	Catch
        ///10000015	Venal
        ///10000016	Lonetrek
        ///10000017	J7HZ-F
        ///10000018	The Spire
        ///10000019	A821-A
        ///10000020	Tash-Murkon
        ///10000021	Outer Passage
        ///10000022	Stain
        ///10000023	Pure Blind
        ///10000025	Immensea
        ///10000027	Etherium R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string regions {
            get {
                return ResourceManager.GetString("regions", resourceCulture);
            }
        }
    }
}
